#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if ! command -v git-xargs > /dev/null; then
  echo "The command requires git-xargs on the PATH, please install it"
  echo "https://github.com/gruntwork-io/git-xargs#getting-started"
  exit 1
fi

if ! command -v go > /dev/null; then
  echo "The command requires go on the PATH, please install it"
  echo "https://golang.org/doc/install"
  exit 1
fi

if ! command -v sed > /dev/null; then
  echo "There is no sed on the PATH, on which weird operating system do you run this script?"
  exit 1
fi

NEW_VERSION="${1-}"

if [ "${NEW_VERSION}" = "" ]; then
  echo "usage update-gradle-smp-plugin newVersion"
  exit 1
fi

echo "type doit to update the gradle-smp-plugin to v${NEW_VERSION} of all scm-manager repositories"
read INPUT

if [ "${INPUT}" != "doit" ]; then
  echo "abort"
  exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
go build -o "${SCRIPT_DIR}/bin/update-gradle-smp-plugin" "${SCRIPT_DIR}/src/update-gradle-smp-plugin.go"

SNAKE_VERSION=$(echo "${NEW_VERSION}" | sed 's/\./_/g')

# For debug output:
# --loglevel DEBUG \

# To update default branch without pr:
# --branch-name develop \
# --skip-pull-requests \

# For test runs:
# --dry \

git-xargs \
  --branch-name "feature/update_gradle_smp_plugin_v${SNAKE_VERSION}" \
  --commit-message "Update gradle-smp-plugin to version ${NEW_VERSION}" \
  --github-org "scm-manager" \
  "${SCRIPT_DIR}/bin/update-gradle-smp-plugin" . "${NEW_VERSION}"
